<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Pledge2Propel</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="title" content="Pledge2Propel | Life after Layoff | Layoff Support and Services">
    <meta name="description" content="Pledge2Propel, an initiative of Ideas2IT and  IdeaRX, is on a mission to help technology professionals who’ve lost their jobs find new opportunities.">
    <link rel="shortcut icon" type="image/png" href="img/favicon.ico">
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link href="css/style.css" rel="stylesheet" />

  </head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-Z6NGK7JGJK"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-Z6NGK7JGJK');
  </script>
  <body>
      <section class="hero">
          <div class="container">
              <div class="row align-items-center">
                <div class="col-md-6 logo">
                    <a href="https://pledge2propel.com/"><img src="./img/pp-logo.png" alt="logo" class="mb-4 mb-sm-0" /></a>
                </div>
              </div>
          </div>
      </section>
      <section>
          <div class="container">
              <div class="row">
                  <div class="col-md-12">
			<h2>Agreement between User and Pledge2Propel</h2>
<p>The Pledge2Propel Technology Services Private Limited, (Pledge2Propel) website is comprised of various Web pages operated by Pledge2Propel and/or Linked Sites as defined herein below (collectively “Pledge2Propel Website”).</p>
<p>The Pledge2Propel Website is offered to you on your unconditional acceptance of the same without modification of any of the terms, conditions, and notices contained herein.</p>
<p>You acknowledge and agree that your use of the Pledge2Propel Website constitutes your unconditional and irrevocable agreement and acceptance to all such terms, conditions, and notices contained herein and /or modified/amended from time to time by Pledge2Propel at its sole discretion.</p>
<h2>Modification of these terms of use</h2>
<p>Pledge2Propel reserves the right to change the terms, conditions, and notices under which the Pledge2Propel Website is offered. Pledge2Propel may at its sole discretion (without in any manner being answerable and/or called upon to justify) amend these Terms of Use at any time by updating this page. You agree and acknowledge that any changes to these Terms of Use shall also be binding on you. You agree that your continued use of the Pledge2Propel Websites or Pledge2Propel’s services shall constitute your agreement to such amendments to these Terms of Use.</p>
<h2>Links to third party sites</h2>
<p>The Pledge2Propel Website may contain links to other Websites including, but not limited to links to third-party Websites (“Linked Sites”). The Linked Sites are not under the control or operation of Pledge2Propel and Pledge2Propel is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to a Linked Site. Pledge2Propel is not responsible for web casting or any other form of transmission received from any Linked Site. Pledge2Propel is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by Pledge2Propel of the site or any association with its operators and is further not responsible for the content or privacy policy or practices of any linked site you may choose or visit. If you decide to access a linked third-party Website, you do so at your own risk.</p>
<h2>No unlawful or prohibited use</h2>
<p>As a condition of your use of the Pledge2Propel Website, you covenant, undertake and warrant to Pledge2Propel that you will not use the Pledge2Propel Website for any purpose that is unlawful or prohibited by law, these terms, conditions, and notices. You may not use the Pledge2Propel Website in any manner which could damage, disable, overburden, or impair the Pledge2Propel Website or interfere with any other party’s use of the Pledge2Propel Website. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the Pledge2Propel Websites.</p>
<p>You agree that you shall NOT do any of the following, nor use the Pledge2Propel Websites to do any of the following:&nbsp;&nbsp;</p>
<ul>
<li>Upload, post, email, transmit or otherwise make available any information, material or other content (collectively “Content”) that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, indecent, pornographic, libellous, invasive of another’s privacy, false, inaccurate, misleading, incomplete, stale, hateful, or racially, ethnically or otherwise objectionable, offensive or inappropriate;</li>
<li>harm minors in any way;</li>
<li>impersonate any person or entity, including but not limited to Pledge2Propel, Pledge2Propel employee, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
<li>forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Pledge2Propel Websites;</li>
<li>upload, post, email, transmit or otherwise make available any Content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>
<li>upload, post, email, transmit or otherwise make available any Content that infringes any intellectual property, including any patent, trademark, trade secret, copyright, or other proprietary rights, publicity rights, privacy rights or other rights of Pledge2Propel, or any third party;</li>
<li>upload, post, email, transmit or otherwise make available any unsolicited or unauthorized advertising;</li>
<li>upload, post, email, transmit or otherwise make available any material that contains software viruses/Trojans/spyware/malware or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
<li>interfere with or disrupt the Pledge2Propel Websites or servers or networks connected to the Pledge2Propel Websites, or disobey any requirements, procedures, policies or regulations of networks connected to the Pledge2Propel Websites;</li>
<li>provide material support or resources (or to conceal or disguise the nature, location, source, or ownership of material support or resources) to any organization(s) designated by the Government of India and/or any Country that has such a reciprocal agreement with the Government of India, as a foreign terrorist organization;</li>
<li>“stalk” or otherwise harass another user or third-party;</li>
<li>collect or store personal data about other users or third party;</li>
<li>send email in violation of any Indian Enactment or Statute in force or any other applicable anti-“spam” law/s to either Pledge2Propel or any third party;</li>
<li>use any device, software or routine, including but not limited to any viruses, spyware, malware, Trojan horses, worms, time bombs, cancel bots or denial-of-service attacks, intended to damage or interfere with the proper working of the Pledge2Propel Websites or any transaction being conducted on our site, or to surreptitiously intercept or expropriate any system, data or personal information from the Pledge2Propel Websites;</li>
<li>“frame” or “mirror” the Pledge2Propel Websites or any portion thereof;</li>
<li>take any action that imposes an unreasonable or disproportionately large load on the Pledge2Propel infrastructure, including but not limited to “spam” or other such unsolicited mass emailing techniques;</li>
<li>use the Pledge2Propel Websites in any manner if you are a competitor of Pledge2Propel, including without limitation soliciting Professional / Candidates, or Employees of Pledge2Propel for any purpose whatsoever;</li>
<li>resell or make available to any non-user any of the Pledge2Propel’s services, the Pledge2Propel Websites or any content on the Pledge2Propel Websites, or use the Pledge2Propel Websites for any unlawful, commercial, research or information gathering purposes; or</li>
<li>Delete or revise any material posted by another User on the Pledge2Propel Websites, access data not intended for you on the Pledge2Propel Websites, or log into an account which you are not authorized to access.</li>
</ul>
<p>Please report any prohibited conduct by other Users to&nbsp;<a href="mailto:connect@pledge2propel.com">connect@pledge2propel.com</a></p>
<p>Pledge2Propel is under no legal and/or moral obligation to monitor the conduct of Users on the Pledge2Propel Websites or any materials posted thereon, but it may respond when violations are reported. You acknowledge and agree that Pledge2Propel has the right (but not the obligation) to monitor the Pledge2Propel Websites including without limitation all postings by various Users. Without Prejudice to the Pledge2Propel’s other rights as set forth in these Terms of Use, Pledge2Propel reserves its right, with or without notice to the applicable User, to remove content posted by any User on the Pledge2Propel Websites, remove any User from the Pledge2Propel Websites, and/or take any other technical or legal action Pledge2Propel deems necessary in the event that Pledge2Propel believes, in its sole discretion, that the User is creating problems, possible legal liabilities, violating these Terms of Use, or otherwise acting inconsistently with the letter or spirit of Pledge2Propel’s policies. Pledge2Propel also reserves its right to report any wrongdoing of which Pledge2Propel becomes aware to the applicable government or law enforcement agencies or otherwise.</p>
<h2>Materials provided to Pledge2Propel or posted at Pledge2Propel website</h2>
<p>Pledge2Propel does not claim ownership of the materials you provide to Pledge2Propel (including feedback and suggestions) or post, upload, input or submit to any Pledge2Propel Website or its associated services (collectively “Submissions”). However, by posting, uploading, inputting, providing or submitting your Submission you are granting Pledge2Propel, its affiliated companies and necessary sub-licensee/s permission to use your Submission in connection with the operation of their Internet businesses including, without limitation, the rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Submission; and to publish your name in connection with your Submission. No compensation will be paid with respect to the use of your Submission, as provided herein. Pledge2Propel is under no obligation to post or use any Submission, you may provide and Pledge2Propel may remove any Submission at any time in Pledge2Propel’s sole discretion. However, you hereby grant a non-exclusive, worldwide, perpetual, royalty-free, irrevocable right and license to use, distribute, disclose, reproduce and display any information, materials or content you post on the Pledge2Propel Websites or otherwise provide to Pledge2Propel, and to exercise all copyright and publicity rights with respect thereto, subject to the Pledge2Propel Privacy Policy. Without limiting the generality of the foregoing, you authorize Pledge2Propel to disclose your information to other Users as described in these Terms of Use and elsewhere on the Pledge2Propel Websites, subject to the Pledge2Propel Privacy Policy. In addition, you hereby grant Pledge2Propel permission/license/right to display your logo, trademarks and company name on the Pledge2Propel Websites and in press or other public releases or filings. By submitting any information, materials or content on the Pledge2Propel Websites or otherwise to Pledge2Propel, you acknowledge, represent and warrant that you have all right and authority to grant such rights to Pledge2Propel.</p>
<h2>Liability disclaimer</h2>
<p>The information, software, products, and services included in or made available through the Pledge2Propel website may include inaccuracies or typographical errors. Changes are periodically added to the information herein. Pledge2Propel and/or its authorized agent may make improvements and/or changes in the Pledge2Propel website at any time. Advice received via the Pledge2Propel website should not be relied upon for any business or financial decisions and you should consult an appropriate professional for specific advice tailored to your situation.&nbsp;Pledge2Propel and/or its suppliers make no representations about the suitability, reliability, availability, timeliness, and accuracy of the information, software, products, services and related graphics contained on the Pledge2Propel website for any purpose. to the maximum extent permitted by applicable law, all such information, software, products, services and related graphics are provided “as is” without warranty or condition of any kind. Pledge2Propel and/or its suppliers hereby disclaim all warranties and conditions with regard to this information, software, products, services and related graphics, including all implied warranties or conditions of merchantability, fitness for a particular purpose, title and non-infringement.&nbsp;In no event shall Pledge2Propel and/or its suppliers be liable for any direct, indirect, punitive, incidental, special, consequential damages or any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the Pledge2Propel website, with the delay or inability to use the Pledge2Propel website or related services, the provision of or failure to provide services, or for any information, software, products, services and related graphics obtained through the Pledge2Propel website, or otherwise arising out of the use of the Pledge2Propel website, whether based on contract, tort, negligence, strict liability or otherwise, even if Pledge2Propel or any of its suppliers has been advised of the possibility of damages. Because some states/jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages, the above limitation may not apply to you. if you are dissatisfied with any portion of the Pledge2Propel website, or with any of these terms of use, you’re sole and exclusive remedy is to discontinue using the Pledge2Propel website.</p>
<p>Service contact&nbsp;<a href="mailto:connect@pledge2propel.com">connect@pledge2propel.com</a></p>
<h2>Ownership</h2>
<p>The Pledge2Propel’ss Services, Pledge2Propel Websites (including all content thereon) and all intellectual property rights in or related to the Pledge2Propel Websites, including but not limited to copyrights, patents, trademarks, service marks and any feedback left by Users on the Pledge2Propel Websites, are owned and/or licensed by Pledge2Propel, and all right, title and interest in the Pledge2Propel Websites, the Pledge2Propel’ss related services and the related intellectual property rights, are and shall remain Pledge2Propel’ss sole property. This includes, without limitation, the “Pledge2Propel.com” URL; Pledge2Propel, and Pledge2Propel logo, and certain other names and logos used by Pledge2Propel, all of which are service marks or trademarks of Pledge2Propel Technology Services Private Limited, (Pledge2Propel) India. This also includes, without limitation, the “look and feel” of the Pledge2Propel Website (including design, layout, color combinations, button shapes, which is protected by Pledge2Propel’s copyrights.</p>
<p>You may not reproduce, reverse engineer, decompile, disassemble, modify or create derivative works of or with respect to the Pledge2Propel related services, Pledge2Propel Website, or the related intellectual property, and these Terms of Use do not grant you permission to do so. You may not reproduce, modify, display, sell, or distribute the content on the Pledge2Propel Websites or use it in any other way for public or commercial purposes. Pledge2Propel authorizes you to view and download a single copy of the content on the Pledge2Propel Websites solely for your personal, non-commercial use. Certain content on the Pledge2Propel Websites may be licensed from third parties. All such third party content and all intellectual property rights related to that content belong to the respective third parties. You may not remove any copyright, trademark, or other intellectual property or proprietary notice or legend contained in the Pledge2Propel Websites, including any Pledge2Propel Websites content.</p>
<p>Without limiting any other rights or remedies Pledge2Propel may have under these Terms of Use or otherwise, Pledge2Propel may limit, suspend, or terminate the Pledge2Propel’s related services, limit or prohibit access to the Pledge2Propel Websites, modify or remove content on the Pledge2Propel Websites, including without limitation eliminating or discontinuing any content or feature thereon or thereof, or restrict the hours of availability of the Pledge2Propel Websites.</p>
<h2>Indemnification</h2>
<p>You agree to indemnify, keep indemnified, defend, and hold harmless Pledge2Propel and its affiliates, officers, directors, employees, and agents from and against any and all claims, demands, actions, losses, costs, expenses (including without limitation reasonable attorneys’ and Professional / Candidates’ and consultants’ fees), damages or other liabilities, of any kind or nature, (collectively “Liabilities”) which arise out of, result from, allege, or otherwise relate to (i) your use of the Pledge2Propel Website or the Pledge2Propel’s related services, (ii) any information, materials or content you post on the Pledge2Propel Website or otherwise provide to Pledge2Propel or another User, (iii) your breach of these Terms of Use, or (iv) any other act of commission and/or omission by you.</p>
<h2>Termination / Access restriction</h2>
<p>Pledge2Propel reserves the right, in its sole discretion, to terminate your access to the Pledge2Propel Website and the related services or any portion thereof at any time, without any prior notice.&nbsp;Use of the Pledge2Propel Website is unauthorized in any jurisdiction that does not give effect to all provisions of these terms and conditions, including without limitation this paragraph. You agree that no joint venture, partnership, employment, or agency relationship exists between you and Pledge2Propel as a result of this agreement or use of the Pledge2Propel Website. Pledge2Propel’s performance of this agreement is subject to existing laws and legal process, and nothing contained in this agreement is in derogation of Pledge2Propel’s right to comply with governmental, court, and law enforcement requests or requirements relating to your use of the Pledge2Propel Website or information provided to or gathered by Pledge2Propel with respect to such use. If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect. Unless otherwise specified herein, this agreement constitutes the entire agreement between the user and Pledge2Propel with respect to the Pledge2Propel Website and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral, or written, between the user and Pledge2Propel with respect to the Pledge2Propel Website. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish to the parties that this agreement and all related documents are drawn up in English.</p>
<h2>Governing Law</h2>
<p>This Agreement shall be governed and construed in accordance with the laws of the Republic of India.</p>
<h2>Dispute Resolution</h2>
<p>You hereto agree, that all disputes and differences arising between Pledge2Propel and you in connection with regard to usage of this site, content and/or any matter relating thereto or arising therefrom or as to the interpretation thereof, shall be settled by compulsory arbitration by a sole arbitrator to be chosen by Pledge2Propel. The decision/award of the sole arbitrator shall be final and binding. You also agree that you shall have no objection to Pledge2Propel choosing the sole arbitrator. The provisions of the Arbitration and Conciliation Act, 1996, with all its modification/s and amendment/s thereto, shall govern the arbitration proceedings. The language of the Arbitration proceedings shall be English and the seat of arbitration shall be Chennai. The place of arbitration will be Chennai.&nbsp;The Courts at Chennai shall have exclusive jurisdiction to all matters arising out or in relation to arbitration, to the exclusion of all other Courts.</p>
<h2>Copyright &amp; trademark notices</h2>
<p>Content on the site is for personal use only and may be downloaded provided the material is kept intact and there is no violation of the copyrights, trademarks, and other intellectual/proprietary rights. Any alteration of the material or use of the material contained in the site for any other purpose is a violation of the copyright of Pledge2Propel and / or its affiliates or associates or of its third-party information providers. This material cannot be copied, reproduced, republished, uploaded, posted, transmitted, or distributed in any way for non-personal use without obtaining the prior written permission from Pledge2Propel. All rights not expressly granted herein are reserved. Pledge2Propel may monitor access to the Site. Pledge2Propel reserves the right to modify the terms of use of any service without any liability. Pledge2Propel reserves the right to take all measures necessary to prevent access to any service or termination of service if the terms of use are not complied with or are contravened or there is any violation of copyright, trademark, or other proprietary rights. Pledge2Propel acknowledges that all third party trademarks, trade names, service marks, and logos referenced herein belong to their respective companies. Pledge2Propel claims no proprietary or any other rights in respect thereof</p>
<h2>Notices and procedure for making claims of copyright infringement</h2>
<p>Notices: Any notice required or permitted to be given hereunder shall be in writing and sent by prepaid registered mail or by a courier service, in the manner as elected by the Party giving such notice to the designated address of the Pledge2Propel – kindly refer to the Chennai, India address as available on the website.</p>
                  </div>
              </div>
          </div>
      </section>

  </body>
</html>